from setuptools import setup

setup(
    name='Atreoraigh',
    version='',
    packages=['venv.lib.python3.6.site-packages.scapy', 'venv.lib.python3.6.site-packages.scapy.arch',
              'venv.lib.python3.6.site-packages.scapy.arch.windows', 'venv.lib.python3.6.site-packages.scapy.asn1',
              'venv.lib.python3.6.site-packages.scapy.tools', 'venv.lib.python3.6.site-packages.scapy.crypto',
              'venv.lib.python3.6.site-packages.scapy.layers', 'venv.lib.python3.6.site-packages.scapy.contrib',
              'venv.lib.python3.6.site-packages.scapy.modules',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.operations',
              'venv.lib64.python3.6.site-packages.scapy', 'venv.lib64.python3.6.site-packages.scapy.arch',
              'venv.lib64.python3.6.site-packages.scapy.arch.windows', 'venv.lib64.python3.6.site-packages.scapy.asn1',
              'venv.lib64.python3.6.site-packages.scapy.tools', 'venv.lib64.python3.6.site-packages.scapy.crypto',
              'venv.lib64.python3.6.site-packages.scapy.layers', 'venv.lib64.python3.6.site-packages.scapy.contrib',
              'venv.lib64.python3.6.site-packages.scapy.modules',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'venv.lib64.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.operations'],
    url='',
    license='',
    author='rmurphy',
    author_email='',
    description=''
)
